#!/bin/sh
LDAP_SERVER="ldap://ldap server"  # AD 服务器地址
BASE_DN="dc=Domain,dc=com"       # 基础域名，根据你的实际情况修改
BIND_DN="CN=Administrator,CN=Users,DC=Domain,DC=com"  # 绑定用户DN，需要有足够权限
BIND_PW=""  #password
fixedName="" #computerName
ldapsearch -x -H "$LDAP_SERVER" -D "$BIND_DN" -w "$BIND_PW" -b "$BASE_DN" "(&(objectClass=computer)(CN=$fixedName))" cn
